version: '3.8'

services:
  tathya-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tathya-website
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs/nginx:/var/log/nginx
    networks:
      - tathya-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  tathya-network:
    driver: bridge
